[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[dev]
  command = "npm run start"
  targetPort = 3000
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' identity.netlify.com;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
